config/routes.rb
Rails.application.routes.draw do
  resources :boards

end

app/models/board.rb
class Board < ActiveRecord::Base
	
	before_create :set_piece_position
	validates :board_name , uniqueness: true
	private

	def set_piece_position
	  self.piece_position = '{
		  "1a" : "brook",
		  "1b" : "bknight",
		  "1c" : "bbishop",
		  "1d" : "bking",
		  "1e" : "bqueen",
		  "1f" : "bbishop",
		  "1g" : "bknight",
		  "1h" : "brook",
		  "2a" : "bpawn",
		  "2b" : "bpawn",
		  "2c" : "bpawn",
		  "2d" : "bpawn",
		  "2e" : "bpawn",
		  "2f" : "bpawn",
		  "2g" : "bpawn",
		  "2h" : "bpawn",
		  "8a" : "wrook",
		  "8b" : "wknight",
		  "8c" : "wbishop",
		  "8d" : "wking",
		  "8e" : "wqueen",
		  "8f" : "wbishop",
		  "8g" : "wknight",
		  "8h" : "wrook",
		  "7a" : "wpawn",
		  "7b" : "wpawn",
		  "7c" : "wpawn",
		  "7d" : "wpawn",
		  "7e" : "wpawn",
		  "7f" : "wpawn",
		  "7g" : "wpawn",
		  "7h" : "wpawn"
    }'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
		@boards= Board.all.order("created_at DESC")
		@board=Board.new
	end
	def create		
		@board=Board.new(board_params)
		
		if @board.save
			cookies[@board.id] ||="w"			
			redirect_to @board
		else
			@boards= Board.all.order("created_at DESC")
			render 'index'
		end	
	end
	def show
		@boards=Board.find(params[:id])
		cookies[@boards.id] ||="b"
	end	
	def update
		board=Board.find(params[:id])
		board.update_attributes(board_params)
		redirect_to board
	end
	def board_params
		params.require(:board).permit(:piece_position , :current_player, :board_name)
	end


	
end

    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<!--<%= link_to "Create Board", new_board_path%>-->
<%= form_for @board, :html=> { class: 'col-xs-7'} do |f|  %>
  <%= f.text_field :board_name %>  
  <%= f.submit "CREATE BOARD" ,:class => 'btn-primary' %>
 <% end %>
<% unless @board.errors.empty? %>       
       <ul>
          <% @board.errors.each do |msg,ab| %>
            <li ><%= msg %>:<%= ab%></li>
          <%  end %>
       </ul>
<% end %>

<table class="col-xs-4 table-bordered">
	<tr>
		<td  class="text-center"><strong>BOARD ID</strong></td>
		<td  class="text-center"><strong>JOIN PLAYER</strong></td>
	</tr>
	
	<% @boards.each do |p|%>
	<tr>
		<td  class="text-center"><%=p.id%></td>
		<td  class="text-center"><u><%= link_to p.board_name, p %></u></td>
		
	</tr>	
	<%end%>
</table>

app/views/boards/show.html.erb
 
<script>

//here assign the piece_postion value of current move

var currentPosition = <%= @boards.piece_position.html_safe %>;
var playerPiece= '<%= @boards.current_player %>';
var gameHistory = [];

</script>
		  
			  
<%= form_for @boards  do |f| %>
  <%= f.text_area :piece_position%>
   <%= f.text_area :current_player%>
  <%= f.submit "Submit" %>
 <% end %>

<script data-turbolinks-track="true" src="/chess.js"></script>
<table id="board" class=" col-xs-7 "></table>	

<div class="col-xs-3" style= " border: 2px solid  #4B0082" >
<h4><strong><u>BOARD INFORMATION</u></strong></h4>
<strong>BOARD NAME:</strong>  <%= @boards.board_name %><br>
<strong>YOUR COLOR:</strong> <% if @boards.current_player == cookies[@boards.id] %> 
							<span style="color : red"> <%= cookies[@boards.id] %> </span><br>
							 <%else%>
							<span style="color : green"> <%= cookies[@boards.id] %> </span> <br>
							 <%end%>
					
<strong>PLAYER TO MOVE:</strong> <% if @boards.current_player == "b" %>
				<span style="color : #800000"> White </span><br>
				<% else %>
				<span style ="color : #800000"> Black </span>
			  <%end %>
</div>	
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess</title>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid" style= "background-color : #e2eef5">

<%= yield %>

</body>
</html>